version: '2'
services:
  paymentsystem-app:
    image: paymentsystem
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://paymentsystem-mssql:1433;database=PaymentSystem
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  paymentsystem-mssql:
    extends:
      file: mssql.yml
      service: paymentsystem-mssql
